name: "Firmware CI feature runner"
description:
  "Uses @nordicsemiconductor/e2e-bdd-test-runner to run features files of a
  firmware."
inputs:
  device id:
    description: "ID of the device the firmware belongs to (client ID)"
    required: true
  app version:
    description:
      "The version string to use for the app. This is used with the FOTA test."
    required: true
  app name:
    description: "App name of the nRF Asset Tracker instance"
    required: true
  azure iot hub dps id scope:
    description: "ID scope for the Azure IoT Hub Device Provision Service"
    required: true
  feature dir:
    description: "Location of the feature files"
    required: false
    default: features
  target:
    description: "Target board to use"
    default: "nrf9160dk_nrf9160_ns"
    required: false
  log dir:
    description: "Location of the log files"
    required: false
    default: logs

runs:
  using: "node16"
  main: "build/index.js"
